### ISSUE TITLE
Doesn't work for Chrome 39.0.2171.71 (64-bit)

### ISSUE THREAD

**Issue by relativityboy** [welefen/Fiddler#20]
Regex - ^http:.*goal_editor\.js$

File - file:///deleteme/goal_editor.js

Tested by making sure I could access the file url directly from Chrome address bar (it worked)

I went to the url http://localhost/goal_editor.js - I got a 404.

**Comment by simoncarbajal** [comment]
Hi, it doesn't work for me, I've tried with Regex and String along with File. Chromium Version 39.0.2171.65 Ubuntu 14.04 (64-bit).

**Comment by mrbowes** [comment]
I have similar issue when I try use file auto responder.  It doesn't seem to work.  The path to the file works in the browser.

Pattern: String /resources/css/global.css
Replace: File: file:///Users/josh/global.css

Auto responder is working for me for Cancel and Redirect requests.

**Comment by relativityboy** [comment]
The version of Chrome for which this bug was reported isn't distributed anymore. Closing. @mrbowes I'd suggest opening a new issue once you're sure it's not a settings issue.

**Comment by mrbowes** [comment]
Thanks @relativityboy  - opened a new issue. I've tried a bunch of different variations on the Replace: File path, but haven't gotten it to work yet.
