### ISSUE TITLE
代理本地js文件不成功

### ISSUE THREAD

**Issue by hkongm** [welefen/Fiddler#24]
按照Demo中的`Replace`里面选File，路径写 `file:///Users/chriscai/Desktop/1.js` 无效
只能选`Redirect`指向自己本地架的一个测试服务器 `http://localhost:1.js`

商店版本
chrome 42
OSX 最新版 10.3

请作者帮忙看看

**Comment by shinyChen** [comment]
扩展程序的fiddler选项中需要勾选【允许访问文件网址】

**Comment by hkongm** [comment]
soga，疏忽了， 多谢
