### ISSUE TITLE
作者可以不使用 ueapp.com的域名吗

### ISSUE THREAD

**Issue by kairyou** [welefen/Fiddler#25]
如题, 插件功能不错, 只是[这行](https://github.com/welefen/Fiddler/blob/master/src/manifest.json#L33)用了ueapp的网址, 导致公司的路由记录我的电脑偶尔访问这个地址, 而这个域名被标记的是'成人内容'..
:sob:

**Comment by Softor** [comment]
这是福利贴啊！
